* Design Document

** Summary
An endless runner where you are trying to navigate a rocket ship as far as possible.

Clicking the screen creates a black hole for the duration of the click.

The force of the black hole on the ship is the only way of controlling its trajectory.

Black holes do not affect any other objects. Maybe instead of a gravitational pull it’s a magnetic pull. Potentially an interesting obstacle at harder difficulties would be asteroids which were affected by the pull of the black holes.

Obstacles could be other ships, asteroids, aliens.

The rocket has a set speed, which can be altered by creating a black hole behind it or in front of it. Could have some obstacles which require changing the rocket’s speed to pass.

At each frame, the resultant force on the rocket will be calculated, and the rocket will point in the direction of that resultant force.

Could have different training levels to introduce certain obstacles. Normal asteroids, metal asteroids, aliens for example.

Have a single challenge mode which combines all the obstacles at once. Have the distance traveled as the score metric for high score tables.

** Basic prototype
*** Components
- Main menu
  - Some sort of title screen + play button
- Main game
  - Ship
  - Black hole
  - Obstacles
- Game over screen

*** Behaviour
- Ship thrusts forward relative to the ship's orientation
- Player can place a single black hole by clicking anywhere on the screen
- Black holes pull the ship towards them
- Player gains points the further they travel to the right of the screen
- Player dies if they collide with:
  - Asteroids
  - The black hole
  - The top, bottom or left of the screen
- The game world is infinite in the horizontal direction and limited to the screen size in the vertical direction
- To advance the rocket the player needs to travel to the right of the screen
- The player encounters asteroids as they fly through the level
- Asteroids have a small amount of random movement velocity and angular velocity

** Possible Enhancements
This section is just random thoughts for enhancements to the basic prototype
- Parallax scrolling star field in the background
- Move movement from asteroids
  - Flying in from the top/bottom?
  - Flying at the player in 'hard mode'?
- Top/bottom of the screen could be a dense, unpassable asteroid field
- Maze game mode:
  - The player must navigate an asteroid field that changes direction as the level progresses
  - i.e. instead of only flying in one direction, it could switch during the level?
- Wander mode:
  - Not bound by 1 direction, player can move freely
- Cool black hole creation graphics
  - Pretty sure we could use some shaders to warp the surrounding graphics
